services:
  mysql-db:
    image: mysql:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: 57blocks
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  spring-boot-app:
    build: .
    container_name: spring-boot-app
    image: springboot-app
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      mysql-db:
        condition: service_healthy
    environment:
      57BLOCKS_SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/57blocks
      57BLOCKS_SPRING_DATASOURCE_USERNAME: root
      57BLOCKS_SPRING_DATASOURCE_PASSWORD: admin
      57BLOCKS_JASYPT_ENCRIPTOR_PASSWORD: yPrm+DiuGqs0e11uwfEz16NiXODLedo+nF2Wd2/2ERE=
      57BLOCKS_SECURITY_JWT_SECRET_KEY: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
volumes:
  db: